# Controls when the workflow will run
on:
  # Allows you to run this workflow manually target the Actions tab
  workflow_dispatch:

name: Build Emulator Windows
jobs:
  build:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
         # - { sys: mingw32, env: i686 } does not work tinyxml does not exist for this
    runs-on: windows-latest    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Msys
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            base-devel
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-SDL2             
            mingw-w64-${{matrix.env}}-SDL2_image
            mingw-w64-${{matrix.env}}-cmake
            mingw-w64-${{matrix.env}}-make
            mingw-w64-${{matrix.env}}-libwebp
            mingw-w64-${{matrix.env}}-libtiff
            mingw-w64-${{matrix.env}}-libpng
            mingw-w64-${{matrix.env}}-openal
            mingw-w64-${{matrix.env}}-freealut
            mingw-w64-${{matrix.env}}-tinyxml2
      - name: Patch Os Dialog source file
        shell: msys2 {0}
        run: |
          sed -i 's/WPARAM/long long int/g' DesktopEmulator/ExternalLibraries/osdialog/osdialog_win.c
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir build
          cd build 
          cmake -G "MSYS Makefiles" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX="./artifact" ../DesktopEmulator
          make install
      - name: Copy dll libraries
        shell: msys2 {0}
        run: |
          rm -f ./build/artifact/Emulator/*.dll
          cp /${{matrix.sys}}/bin/liblcms2*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libiconv*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libintl*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libLer*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libjbig*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libhw*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libbrotli*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libyu*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libSvtAv1*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/rav1*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libao*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libdav1d*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libjxl*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libavif*.dll ./build/artifact/Emulator  
          cp /${{matrix.sys}}/bin/libalut*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libdeflate*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libopenal*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libgcc*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/liblzma*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libstdc++*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libtiff*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libwebp*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libzstd*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/zlib*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libjpeg*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/SDL2*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libsharpyuv*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libwinpthread*.dll ./build/artifact/Emulator
          cp /${{matrix.sys}}/bin/libtinyxml*.dll ./build/artifact/Emulator
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: Vircon32-Emulator-Windows-${{ matrix.env }}
          path: ./build/artifact/
