# Controls when the workflow will run
on:
  # Allows you to run this workflow manually target the Actions tab
  workflow_dispatch:

name: Build Emulator Mac Os
jobs:
  build:
    strategy:
      matrix:
        include:
          - { runner: macos-13, homebrew_inc_dir: /usr/local/include}
          - { runner: macos-latest, homebrew_inc_dir: /opt/homebrew/include}
    runs-on: ${{matrix.runner}} 
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
          
      - name: Setup homebrew stuff
        run: |
          brew update
          brew install sdl2 sdl2_image openal-soft freealut tinyxml2 libpng cmake
          
      - name: Build
        run: |
          mkdir build
          cd build 
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DEXTRA_INCLUDE_DIR="${{matrix.homebrew_inc_dir}}" -DCMAKE_INSTALL_PREFIX="./artifact" ../DesktopEmulator
          make install
      - name: Prepare artifact
        run: |
          cd build/artifact
          tar vfc Vircon32-Emulator-Macos-${{matrix.runner}}.tar Vircon32
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: Vircon32-Emulator-Macos-${{matrix.runner}} 
          path: build/artifact/Vircon32-Emulator-Macos-${{matrix.runner}}.tar
